[package]
org = "madushanka"
name = "ssp_service"
version = "0.1.0"
distribution = "2201.4.1"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "com.microsoft.sqlserver"
artifactId = "mssql-jdbc"
version = "9.2.0.jre11"